baseurl = "https://jithinisaac.dblabs.in"
title = "Home"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Jithin Saji Isaac"
    description = "Jithin Saji Isaac's personal website"
    keywords = "blog,developer,personal"
    info = "Embedded IoT Enthusiast | Full Stack Web Dev & Cloud Computing Hobbyist"
    avatarurl = "images/avatar.jpeg"
    #gravatar = ""
    footercontent = ""

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 6

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/jithinsisaac/" 
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/jithinisaac/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/jithin-saji-isaac" 

[[params.social]]
    name = "youtubechannel"
    icon = "fab fa-youtube"
    weight = 5
    url = "https://www.youtube.com/channel/UCn7YD1HaO6jQZvlJ2piMxmg/playlists" 

[languages]
    [languages.en]
        languagename = "English" 

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Skillset"
            weight = 2
            url = "skills/"
            
            [[languages.en.menu.main]]
            name = "Blog"
            weight = 3
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 4
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Workshops"
            weight = 5
            url = "workshops/"

            [[languages.en.menu.main]]
            name = "Academics"
            weight = 6
            url = "academics/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 7
            url = "contact/"

 
       
    [languages.hi]
        languagename = "हिन्दी"
        title = "घर"

        [languages.hi.params]
            author = "जितिन सजी ऐसक" 
            footercontent = "स्वागत हे!"            
            colorscheme = "dark"

